# Header
menu:
  Home: /
  Archives: /archives
github: https://github.com/ciphersaw

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
sidebar-about-description: "Welcome to Secrypt Agency, a technique-sharing platform for network security artists."
sidebar-avatar: img/avatar.jpg
widgets:
- about_me
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://arvinxiang.com
  热前端: http://reqianduan.com
  远程.work: http://yuancheng.work

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Baidu share
# baidushare: true